tlt_ticket_defect_type_api:
    resource: "@TltTicketBundle/Controller/Api/Rest/DefectTypeController.php"
    type: rest
tlt_ticket_equipment_type_api:
    resource: "@TltTicketBundle/Controller/Api/Rest/EquipmentTypeController.php"
    type: rest
tlt_ticket_equipment_api:
    resource: "@TltTicketBundle/Controller/Api/Rest/EquipmentController.php"
    type: rest
