tlt_ticket_defect_type_create:
    type: entity
    class: "TltTicketBundle:DefectType"
    permission: CREATE
    group_name: ""
    bindings: ~
tlt_ticket_defect_type_view:
    type: entity
    class: "TltTicketBundle:DefectType"
    permission: VIEW
    group_name: ""
    bindings: ~
tlt_ticket_defect_type_update:
    type: entity
    class: "TltTicketBundle:DefectType"
    permission: EDIT
    group_name: ""
    bindings: ~
tlt_ticket_defect_type_delete:
    type: entity
    class: "TltTicketBundle:DefectType"
    permission: DELETE
    group_name: ""
    bindings: ~
tlt_ticket_equipment_type_create:
    type: entity
    class: "TltTicketBundle:EquipmentType"
    permission: CREATE
    group_name: ""
    bindings: ~
tlt_ticket_equipment_type_view:
    type: entity
    class: "TltTicketBundle:EquipmentType"
    permission: VIEW
    group_name: ""
    bindings: ~
tlt_ticket_equipment_type_update:
    type: entity
    class: "TltTicketBundle:EquipmentType"
    permission: EDIT
    group_name: ""
    bindings: ~
tlt_ticket_equipment_type_delete:
    type: entity
    class: "TltTicketBundle:EquipmentType"
    permission: DELETE
    group_name: ""
    bindings: ~
tlt_ticket_equipment_create:
    type: entity
    class: "TltTicketBundle:Equipment"
    permission: CREATE
    group_name: ""
    bindings: ~
tlt_ticket_equipment_view:
    type: entity
    class: "TltTicketBundle:Equipment"
    permission: VIEW
    group_name: ""
    bindings: ~
tlt_ticket_equipment_update:
    type: entity
    class: "TltTicketBundle:Equipment"
    permission: EDIT
    group_name: ""
    bindings: ~
tlt_ticket_equipment_delete:
    type: entity
    class: "TltTicketBundle:Equipment"
    permission: DELETE
    group_name: ""
    bindings: ~
tlt_ticket_defect_create:
    type: entity
    class: "TltTicketBundle:Defect"
    permission: CREATE
    group_name: ""
    bindings: ~
tlt_ticket_defect_view:
    type: entity
    class: "TltTicketBundle:Defect"
    permission: VIEW
    group_name: ""
    bindings: ~
tlt_ticket_defect_update:
    type: entity
    class: "TltTicketBundle:Defect"
    permission: EDIT
    group_name: ""
    bindings: ~
tlt_ticket_defect_delete:
    type: entity
    class: "TltTicketBundle:Defect"
    permission: DELETE
    group_name: ""
    bindings: ~
